os: linux
dist: xenial
language: node_js
node_js: 10
install:
    - npm install
    - npm run lint
    - npm run build
addons:
    ssh_known_hosts: vps514431.ovh.net
before_install:
  openssl aes-256-cbc -K $encrypted_e4b94ab10d0b_key -iv $encrypted_e4b94ab10d0b_iv -in deploy/deploy-key.enc -out deploy/deploy-key -d
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./deploy/deploy-production.sh
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash ./deploy/deploy-sandbox.sh
      on:
        branch: staging
